// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8N3fSkEXOAfuk1GYCSf1Nk2oYV-47sy8',
    appId: '1:942638822148:web:efc021309819854eb69651',
    messagingSenderId: '942638822148',
    projectId: 'flutter-chat-app-e5831',
    authDomain: 'flutter-chat-app-e5831.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e5831.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD4is9To5ThryCtf-xitO1VAF9z4vjhrQ',
    appId: '1:942638822148:android:7d9838d44f8250d8b69651',
    messagingSenderId: '942638822148',
    projectId: 'flutter-chat-app-e5831',
    storageBucket: 'flutter-chat-app-e5831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhL4TPg9pInXphaYJBO5BikFMg8Qb-D0o',
    appId: '1:942638822148:ios:b868ae68bfcec7b4b69651',
    messagingSenderId: '942638822148',
    projectId: 'flutter-chat-app-e5831',
    storageBucket: 'flutter-chat-app-e5831.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhL4TPg9pInXphaYJBO5BikFMg8Qb-D0o',
    appId: '1:942638822148:ios:b868ae68bfcec7b4b69651',
    messagingSenderId: '942638822148',
    projectId: 'flutter-chat-app-e5831',
    storageBucket: 'flutter-chat-app-e5831.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8N3fSkEXOAfuk1GYCSf1Nk2oYV-47sy8',
    appId: '1:942638822148:web:13354bc46be2cc2cb69651',
    messagingSenderId: '942638822148',
    projectId: 'flutter-chat-app-e5831',
    authDomain: 'flutter-chat-app-e5831.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e5831.firebasestorage.app',
  );
}
